name: social_share_plugin
description: Social Share to Facebook and Instagram Flutter plugin.
version: 0.3.1+1
homepage: https://romatroskin.github.io/
repository: https://github.com/romatroskin/social_share_plugin.git

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0 <2.2.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.cygnati.social_share_plugin
        pluginClass: SocialSharePlugin
      ios:
        pluginClass: SocialSharePlugin
